services:
  database:
    container_name: database
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: social
    ports:
      - "3307:3306" # Thay 3306 thành 3307
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=jdbc:mysql://database:3306/social?useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=12345678
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TIME_ZONE=Asia/Ho_Chi_Minh
      - SIGNED_KEY=4FUNMjFiPr1J29IIqbjc7QbPpX2RPfQSVAH8b5dQHVK5XxyTdjC6Ax9DG8YodTb5
      - ACCESS_KEY=AKIAVRUVSN7O6R7B34E2
      - SECRET_KEY=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
      - REGION=ap-southeast-1
      - BUCKET_NAME=tuyen-third-bucket
    ports:
      - "8888:8888"
    depends_on:
      - database
      - redis
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge