server:
  port: ${PORT:8888}
  servlet:
    context-path: /media

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE:Asia/Ho_Chi_Minh}
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  signerKey: ${SIGNED_KEY}

amazon:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  region: ${REGION}
  bucket-name: ${BUCKET_NAME}